"use client";
import { Inter } from "next/font/google";
import "./globals.scss";
// redux toolkit store
import Store from "@/store/store";
// connect to react
import { Provider } from "react-redux";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={Store}>{children}</Provider>
      </body>
      <link rel="icon" href="/assets/movix-logo.png" sizes="any" />
    </html>
  );
}
